'use client'

import { useState } from 'react'

export type CodeSection = {
  label: string
  content: string
  defaultOpen: boolean
}

interface CodePanelProps {
  sections: CodeSection[]
  functionName: string
  generatedModel: string | null
}

export function CodePanel({ sections, functionName, generatedModel }: CodePanelProps) {
  return (
    <div className="divide-y divide-zinc-200 dark:divide-zinc-700 bg-white dark:bg-zinc-950">
      {generatedModel && (
        <p className="px-4 py-1.5 text-xs text-zinc-400 dark:text-zinc-500">
          {functionName} · generated by {generatedModel}
        </p>
      )}
      {sections.map((section) => (
        <CollapsibleSection key={section.label} section={section} />
      ))}
    </div>
  )
}

function CollapsibleSection({ section }: { section: CodeSection }) {
  const [open, setOpen] = useState(section.defaultOpen)
  const [copied, setCopied] = useState(false)

  function handleCopy() {
    navigator.clipboard.writeText(section.content).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div>
      <div className="flex items-center gap-2 px-4 py-2 bg-zinc-50 dark:bg-zinc-900">
        <button
          onClick={() => setOpen((v) => !v)}
          className="flex items-center gap-1.5 text-xs font-mono font-semibold text-zinc-500 dark:text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors flex-1 text-left"
        >
          <span>{open ? '▾' : '▸'}</span>
          <span>{section.label}</span>
        </button>
        <button
          onClick={handleCopy}
          className="text-xs text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 transition-colors shrink-0"
          aria-label={`Copy ${section.label}`}
        >
          {copied ? '✓ Copied' : 'Copy'}
        </button>
      </div>
      {open && (
        <pre className="px-4 py-3 text-xs font-mono text-zinc-700 dark:text-zinc-300 overflow-x-auto whitespace-pre-wrap break-words leading-relaxed">
          {section.content}
        </pre>
      )}
    </div>
  )
}
